services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${S3_ENDPOINT}
    volumes:
      - ./docker-data/minio:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [CMD, mc, ready, local]
      interval: 30s
      timeout: 20s
      retries: 3